---
- name: "Restart and enable {{ keycloak.service_name }} service"
  ansible.builtin.systemd:
    name: "{{ keycloak.service_name }}"
    enabled: true
    state: restarted
    daemon_reload: true
  become: true

- name: "Wait until {{ keycloak.service_name }} service becomes active {{ keycloak.health_url }}"
  ansible.builtin.uri:
    url: "{{ keycloak.health_url }}"
  register: keycloak_status
  until: keycloak_status.status == 200
  retries: 25
  delay: 10
  when: keycloak_quarkus_restart_health_check
