---
- name: "Restart services in serial, with optional healtch check (keycloak_quarkus_restart_health_check)"
  throttle: 1
  loop: "{{ ansible_play_hosts }}"
  block:
    - name: "Restart and enable {{ keycloak.service_name }} service on first host"
      ansible.builtin.include_tasks: ../restart.yml
      delegate_to: "{{ item }}"
